# Generated by Django 5.0.3 on 2024-03-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketHub', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
