# Generated by Django 5.0.3 on 2024-03-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketHub', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
