# Generated by Django 5.0.3 on 2024-03-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketHub', '0010_alter_product_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
