# Generated by Django 5.0.3 on 2024-03-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketHub', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
